In [3]:
import pandas as pd

import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
import plotly

pio.renderers.default = 'notebook'

In [4]:
df = pd.read_csv('../treated_datasets/countries_of_origin.tsv', sep='\t')
df.head()

   Unnamed: 0     tconst country_of_origin
0           0  tt0212686            France
1           1  tt0206476     United States
2           2  tt0160904    United Kingdom
3           3  tt0219446     United States
4           4  tt0213327            Canada

In [11]:
pd.DataFrame(df.groupby('country_of_origin').count())

                        Unnamed: 0  tconst
country_of_origin
Argentina                        5       5
Australia                       56      56
Austria                          1       1
Bangladesh                       3       3
Belgium                         15      15
Bosnia and Herzegovina           1       1
Brazil                          14      14
Bulgaria                         3       3
Canada                         155     155
China                           12      12
Colombia                         7       7
Croatia                          2       2
Czech Republic                   1       1
Denmark                         22      22
Egypt                            5       5
Finland                          4       4
France                          46      46
Georgia                          1       1
Germany                         29      29
Greece                           6       6
Hungary                          3       3
Iceland                          5       5
India                          216     216
Indonesia                        1       1
Iran                            39      39
Ireland                         11      11
Israel                           9       9
Italy                           26      26
Japan                          302     302
Jordan                           1       1
Kuwait                           1       1
Luxembourg                       1       1
Mexico                          18      18
Netherlands                      5       5
New Zealand                      6       6
Norway                          23      23
Pakistan                         9       9
Poland                           9       9
Portugal                         2       2
Romania                          2       2
Russia                           7       7
Saudi Arabia                     1       1
Serbia                          19      19
Singapore                        2       2
South Africa                     2       2
South Korea                    164     164
Spain                           47      47
Sri Lanka                        1       1
Sweden                          33      33
Switzerland                      1       1
Syria                            2       2
Taiwan                           1       1
Thailand                        10      10
Tunisia                          2       2
Turkey                         136     136
Ukraine                          1       1
United Arab Emirates             1       1
United Kingdom                 456     456
United States                 2097    2097

In [21]:
plot_df = pd.DataFrame(df.groupby('country_of_origin').count()).reset_index()
plot_df = plot_df.rename(columns={'tconst': 'count'})
plot_df = plot_df.sort_values('count', ascending=False)
plot_df.head()

   country_of_origin  Unnamed: 0  count
58     United States        2097   2097
57    United Kingdom         456    456
28             Japan         302    302
22             India         216    216
45       South Korea         164    164

In [23]:
px.histogram(plot_df[:20], x='country_of_origin', y='count')